<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Schema::disableForeignKeyConstraints();
        DB::table('countries')->truncate();
        Country::create(['code' => 'AF', 'name' => 'Afghanistan']);
        Country::create(['code' => 'AX', 'name' => 'Åland Islands']);
        Country::create(['code' => 'AL', 'name' => 'Albania']);
        Country::create(['code' => 'DZ', 'name' => 'Algeria']);
        Country::create(['code' => 'AS', 'name' => 'American Samoa']);
        Country::create(['code' => 'AD', 'name' => 'Andorra']);
        Country::create(['code' => 'AO', 'name' => 'Angola']);
        Country::create(['code' => 'AI', 'name' => 'Anguilla']);
        Country::create(['code' => 'AQ', 'name' => 'Antarctica']);
        Country::create(['code' => 'AG', 'name' => 'Antigua & Barbuda']);
        Country::create(['code' => 'AR', 'name' => 'Argentina']);
        Country::create(['code' => 'AM', 'name' => 'Armenia']);
        Country::create(['code' => 'AW', 'name' => 'Aruba']);
        Country::create(['code' => 'AC', 'name' => 'Ascension Island']);
        Country::create(['code' => 'AU', 'name' => 'Australia']);
        Country::create(['code' => 'AT', 'name' => 'Austria']);
        Country::create(['code' => 'AZ', 'name' => 'Azerbaijan']);
        Country::create(['code' => 'BS', 'name' => 'Bahamas']);
        Country::create(['code' => 'BH', 'name' => 'Bahrain']);
        Country::create(['code' => 'BD', 'name' => 'Bangladesh']);
        Country::create(['code' => 'BB', 'name' => 'Barbados']);
        Country::create(['code' => 'BY', 'name' => 'Belarus']);
        Country::create(['code' => 'BE', 'name' => 'Belgium']);
        Country::create(['code' => 'BZ', 'name' => 'Belize']);
        Country::create(['code' => 'BJ', 'name' => 'Benin']);
        Country::create(['code' => 'BM', 'name' => 'Bermuda']);
        Country::create(['code' => 'BT', 'name' => 'Bhutan']);
        Country::create(['code' => 'BO', 'name' => 'Bolivia']);
        Country::create(['code' => 'BA', 'name' => 'Bosnia & Herzegovina']);
        Country::create(['code' => 'BW', 'name' => 'Botswana']);
        Country::create(['code' => 'BR', 'name' => 'Brazil']);
        Country::create(['code' => 'IO', 'name' => 'British Indian Ocean Territory']);
        Country::create(['code' => 'VG', 'name' => 'British Virgin Islands']);
        Country::create(['code' => 'BN', 'name' => 'Brunei']);
        Country::create(['code' => 'BG', 'name' => 'Bulgaria']);
        Country::create(['code' => 'BF', 'name' => 'Burkina Faso']);
        Country::create(['code' => 'BI', 'name' => 'Burundi']);
        Country::create(['code' => 'KH', 'name' => 'Cambodia']);
        Country::create(['code' => 'CM', 'name' => 'Cameroon']);
        Country::create(['code' => 'CA', 'name' => 'Canada']);
        Country::create(['code' => 'IC', 'name' => 'Canary Islands']);
        Country::create(['code' => 'CV', 'name' => 'Cape Verde']);
        Country::create(['code' => 'BQ', 'name' => 'Caribbean Netherlands']);
        Country::create(['code' => 'KY', 'name' => 'Cayman Islands']);
        Country::create(['code' => 'CF', 'name' => 'Central African Republic']);
        Country::create(['code' => 'EA', 'name' => 'Ceuta & Melilla']);
        Country::create(['code' => 'TD', 'name' => 'Chad']);
        Country::create(['code' => 'CL', 'name' => 'Chile']);
        Country::create(['code' => 'CN', 'name' => 'China']);
        Country::create(['code' => 'CX', 'name' => 'Christmas Island']);
        Country::create(['code' => 'CC', 'name' => 'Cocos (Keeling) Islands']);
        Country::create(['code' => 'CO', 'name' => 'Colombia']);
        Country::create(['code' => 'KM', 'name' => 'Comoros']);
        Country::create(['code' => 'CG', 'name' => 'Congo - Brazzaville']);
        Country::create(['code' => 'CD', 'name' => 'Congo - Kinshasa']);
        Country::create(['code' => 'CK', 'name' => 'Cook Islands']);
        Country::create(['code' => 'CR', 'name' => 'Costa Rica']);
        Country::create(['code' => 'CI', 'name' => 'Côte d’Ivoire']);
        Country::create(['code' => 'HR', 'name' => 'Croatia']);
        Country::create(['code' => 'CU', 'name' => 'Cuba']);
        Country::create(['code' => 'CW', 'name' => 'Curaçao']);
        Country::create(['code' => 'CY', 'name' => 'Cyprus']);
        Country::create(['code' => 'CZ', 'name' => 'Czechia']);
        Country::create(['code' => 'DK', 'name' => 'Denmark']);
        Country::create(['code' => 'DG', 'name' => 'Diego Garcia']);
        Country::create(['code' => 'DJ', 'name' => 'Djibouti']);
        Country::create(['code' => 'DM', 'name' => 'Dominica']);
        Country::create(['code' => 'DO', 'name' => 'Dominican Republic']);
        Country::create(['code' => 'EC', 'name' => 'Ecuador']);
        Country::create(['code' => 'EG', 'name' => 'Egypt']);
        Country::create(['code' => 'SV', 'name' => 'El Salvador']);
        Country::create(['code' => 'GQ', 'name' => 'Equatorial Guinea']);
        Country::create(['code' => 'ER', 'name' => 'Eritrea']);
        Country::create(['code' => 'EE', 'name' => 'Estonia']);
        Country::create(['code' => 'ET', 'name' => 'Ethiopia']);
        Country::create(['code' => 'EZ', 'name' => 'Eurozone']);
        Country::create(['code' => 'FK', 'name' => 'Falkland Islands']);
        Country::create(['code' => 'FO', 'name' => 'Faroe Islands']);
        Country::create(['code' => 'FJ', 'name' => 'Fiji']);
        Country::create(['code' => 'FI', 'name' => 'Finland']);
        Country::create(['code' => 'FR', 'name' => 'France']);
        Country::create(['code' => 'GF', 'name' => 'French Guiana']);
        Country::create(['code' => 'PF', 'name' => 'French Polynesia']);
        Country::create(['code' => 'TF', 'name' => 'French Southern Territories']);
        Country::create(['code' => 'GA', 'name' => 'Gabon']);
        Country::create(['code' => 'GM', 'name' => 'Gambia']);
        Country::create(['code' => 'GE', 'name' => 'Georgia']);
        Country::create(['code' => 'DE', 'name' => 'Germany']);
        Country::create(['code' => 'GH', 'name' => 'Ghana']);
        Country::create(['code' => 'GI', 'name' => 'Gibraltar']);
        Country::create(['code' => 'GR', 'name' => 'Greece']);
        Country::create(['code' => 'GL', 'name' => 'Greenland']);
        Country::create(['code' => 'GD', 'name' => 'Grenada']);
        Country::create(['code' => 'GP', 'name' => 'Guadeloupe']);
        Country::create(['code' => 'GU', 'name' => 'Guam']);
        Country::create(['code' => 'GT', 'name' => 'Guatemala']);
        Country::create(['code' => 'GG', 'name' => 'Guernsey']);
        Country::create(['code' => 'GN', 'name' => 'Guinea']);
        Country::create(['code' => 'GW', 'name' => 'Guinea-Bissau']);
        Country::create(['code' => 'GY', 'name' => 'Guyana']);
        Country::create(['code' => 'HT', 'name' => 'Haiti']);
        Country::create(['code' => 'HN', 'name' => 'Honduras']);
        Country::create(['code' => 'HK', 'name' => 'Hong Kong SAR China']);
        Country::create(['code' => 'HU', 'name' => 'Hungary']);
        Country::create(['code' => 'IS', 'name' => 'Iceland']);
        Country::create(['code' => 'IN', 'name' => 'India']);
        Country::create(['code' => 'ID', 'name' => 'Indonesia']);
        Country::create(['code' => 'IR', 'name' => 'Iran']);
        Country::create(['code' => 'IQ', 'name' => 'Iraq']);
        Country::create(['code' => 'IE', 'name' => 'Ireland']);
        Country::create(['code' => 'IM', 'name' => 'Isle of Man']);
        Country::create(['code' => 'IL', 'name' => 'Israel']);
        Country::create(['code' => 'IT', 'name' => 'Italy']);
        Country::create(['code' => 'JM', 'name' => 'Jamaica']);
        Country::create(['code' => 'JP', 'name' => 'Japan']);
        Country::create(['code' => 'JE', 'name' => 'Jersey']);
        Country::create(['code' => 'JO', 'name' => 'Jordan']);
        Country::create(['code' => 'KZ', 'name' => 'Kazakhstan']);
        Country::create(['code' => 'KE', 'name' => 'Kenya']);
        Country::create(['code' => 'KI', 'name' => 'Kiribati']);
        Country::create(['code' => 'XK', 'name' => 'Kosovo']);
        Country::create(['code' => 'KW', 'name' => 'Kuwait']);
        Country::create(['code' => 'KG', 'name' => 'Kyrgyzstan']);
        Country::create(['code' => 'LA', 'name' => 'Laos']);
        Country::create(['code' => 'LV', 'name' => 'Latvia']);
        Country::create(['code' => 'LB', 'name' => 'Lebanon']);
        Country::create(['code' => 'LS', 'name' => 'Lesotho']);
        Country::create(['code' => 'LR', 'name' => 'Liberia']);
        Country::create(['code' => 'LY', 'name' => 'Libya']);
        Country::create(['code' => 'LI', 'name' => 'Liechtenstein']);
        Country::create(['code' => 'LT', 'name' => 'Lithuania']);
        Country::create(['code' => 'LU', 'name' => 'Luxembourg']);
        Country::create(['code' => 'MO', 'name' => 'Macau SAR China']);
        Country::create(['code' => 'MK', 'name' => 'Macedonia']);
        Country::create(['code' => 'MG', 'name' => 'Madagascar']);
        Country::create(['code' => 'MW', 'name' => 'Malawi']);
        Country::create(['code' => 'MY', 'name' => 'Malaysia']);
        Country::create(['code' => 'MV', 'name' => 'Maldives']);
        Country::create(['code' => 'ML', 'name' => 'Mali']);
        Country::create(['code' => 'MT', 'name' => 'Malta']);
        Country::create(['code' => 'MH', 'name' => 'Marshall Islands']);
        Country::create(['code' => 'MQ', 'name' => 'Martinique']);
        Country::create(['code' => 'MR', 'name' => 'Mauritania']);
        Country::create(['code' => 'MU', 'name' => 'Mauritius']);
        Country::create(['code' => 'YT', 'name' => 'Mayotte']);
        Country::create(['code' => 'MX', 'name' => 'Mexico']);
        Country::create(['code' => 'FM', 'name' => 'Micronesia']);
        Country::create(['code' => 'MD', 'name' => 'Moldova']);
        Country::create(['code' => 'MC', 'name' => 'Monaco']);
        Country::create(['code' => 'MN', 'name' => 'Mongolia']);
        Country::create(['code' => 'ME', 'name' => 'Montenegro']);
        Country::create(['code' => 'MS', 'name' => 'Montserrat']);
        Country::create(['code' => 'MA', 'name' => 'Morocco']);
        Country::create(['code' => 'MZ', 'name' => 'Mozambique']);
        Country::create(['code' => 'MM', 'name' => 'Myanmar (Burma)']);
        Country::create(['code' => 'NA', 'name' => 'Namibia']);
        Country::create(['code' => 'NR', 'name' => 'Nauru']);
        Country::create(['code' => 'NP', 'name' => 'Nepal']);
        Country::create(['code' => 'NL', 'name' => 'Netherlands']);
        Country::create(['code' => 'NC', 'name' => 'New Caledonia']);
        Country::create(['code' => 'NZ', 'name' => 'New Zealand']);
        Country::create(['code' => 'NI', 'name' => 'Nicaragua']);
        Country::create(['code' => 'NE', 'name' => 'Niger']);
        Country::create(['code' => 'NG', 'name' => 'Nigeria']);
        Country::create(['code' => 'NU', 'name' => 'Niue']);
        Country::create(['code' => 'NF', 'name' => 'Norfolk Island']);
        Country::create(['code' => 'KP', 'name' => 'North Korea']);
        Country::create(['code' => 'MP', 'name' => 'Northern Mariana Islands']);
        Country::create(['code' => 'NO', 'name' => 'Norway']);
        Country::create(['code' => 'OM', 'name' => 'Oman']);
        Country::create(['code' => 'PK', 'name' => 'Pakistan']);
        Country::create(['code' => 'PW', 'name' => 'Palau']);
        Country::create(['code' => 'PS', 'name' => 'Palestinian Territories']);
        Country::create(['code' => 'PA', 'name' => 'Panama']);
        Country::create(['code' => 'PG', 'name' => 'Papua New Guinea']);
        Country::create(['code' => 'PY', 'name' => 'Paraguay']);
        Country::create(['code' => 'PE', 'name' => 'Peru']);
        Country::create(['code' => 'PH', 'name' => 'Philippines']);
        Country::create(['code' => 'PN', 'name' => 'Pitcairn Islands']);
        Country::create(['code' => 'PL', 'name' => 'Poland']);
        Country::create(['code' => 'PT', 'name' => 'Portugal']);
        Country::create(['code' => 'PR', 'name' => 'Puerto Rico']);
        Country::create(['code' => 'QA', 'name' => 'Qatar']);
        Country::create(['code' => 'RE', 'name' => 'Réunion']);
        Country::create(['code' => 'RO', 'name' => 'Romania']);
        Country::create(['code' => 'RU', 'name' => 'Russia']);
        Country::create(['code' => 'RW', 'name' => 'Rwanda']);
        Country::create(['code' => 'WS', 'name' => 'Samoa']);
        Country::create(['code' => 'SM', 'name' => 'San Marino']);
        Country::create(['code' => 'ST', 'name' => 'São Tomé & Príncipe']);
        Country::create(['code' => 'SA', 'name' => 'Saudi Arabia']);
        Country::create(['code' => 'SN', 'name' => 'Senegal']);
        Country::create(['code' => 'RS', 'name' => 'Serbia']);
        Country::create(['code' => 'SC', 'name' => 'Seychelles']);
        Country::create(['code' => 'SL', 'name' => 'Sierra Leone']);
        Country::create(['code' => 'SG', 'name' => 'Singapore']);
        Country::create(['code' => 'SX', 'name' => 'Sint Maarten']);
        Country::create(['code' => 'SK', 'name' => 'Slovakia']);
        Country::create(['code' => 'SI', 'name' => 'Slovenia']);
        Country::create(['code' => 'SB', 'name' => 'Solomon Islands']);
        Country::create(['code' => 'SO', 'name' => 'Somalia']);
        Country::create(['code' => 'ZA', 'name' => 'South Africa']);
        Country::create(['code' => 'GS', 'name' => 'South Georgia & South Sandwich Islands']);
        Country::create(['code' => 'KR', 'name' => 'South Korea']);
        Country::create(['code' => 'SS', 'name' => 'South Sudan']);
        Country::create(['code' => 'ES', 'name' => 'Spain']);
        Country::create(['code' => 'LK', 'name' => 'Sri Lanka']);
        Country::create(['code' => 'BL', 'name' => 'St. Barthélemy']);
        Country::create(['code' => 'SH', 'name' => 'St. Helena']);
        Country::create(['code' => 'KN', 'name' => 'St. Kitts & Nevis']);
        Country::create(['code' => 'LC', 'name' => 'St. Lucia']);
        Country::create(['code' => 'MF', 'name' => 'St. Martin']);
        Country::create(['code' => 'PM', 'name' => 'St. Pierre & Miquelon']);
        Country::create(['code' => 'VC', 'name' => 'St. Vincent & Grenadines']);
        Country::create(['code' => 'SD', 'name' => 'Sudan']);
        Country::create(['code' => 'SR', 'name' => 'Suriname']);
        Country::create(['code' => 'SJ', 'name' => 'Svalbard & Jan Mayen']);
        Country::create(['code' => 'SZ', 'name' => 'Swaziland']);
        Country::create(['code' => 'SE', 'name' => 'Sweden']);
        Country::create(['code' => 'CH', 'name' => 'Switzerland']);
        Country::create(['code' => 'SY', 'name' => 'Syria']);
        Country::create(['code' => 'TW', 'name' => 'Taiwan']);
        Country::create(['code' => 'TJ', 'name' => 'Tajikistan']);
        Country::create(['code' => 'TZ', 'name' => 'Tanzania']);
        Country::create(['code' => 'TH', 'name' => 'Thailand']);
        Country::create(['code' => 'TL', 'name' => 'Timor-Leste']);
        Country::create(['code' => 'TG', 'name' => 'Togo']);
        Country::create(['code' => 'TK', 'name' => 'Tokelau']);
        Country::create(['code' => 'TO', 'name' => 'Tonga']);
        Country::create(['code' => 'TT', 'name' => 'Trinidad & Tobago']);
        Country::create(['code' => 'TA', 'name' => 'Tristan da Cunha']);
        Country::create(['code' => 'TN', 'name' => 'Tunisia']);
        Country::create(['code' => 'TR', 'name' => 'Turkey']);
        Country::create(['code' => 'TM', 'name' => 'Turkmenistan']);
        Country::create(['code' => 'TC', 'name' => 'Turks & Caicos Islands']);
        Country::create(['code' => 'TV', 'name' => 'Tuvalu']);
        Country::create(['code' => 'UM', 'name' => 'U.S. Outlying Islands']);
        Country::create(['code' => 'VI', 'name' => 'U.S. Virgin Islands']);
        Country::create(['code' => 'UG', 'name' => 'Uganda']);
        Country::create(['code' => 'UA', 'name' => 'Ukraine']);
        Country::create(['code' => 'AE', 'name' => 'United Arab Emirates']);
        Country::create(['code' => 'GB', 'name' => 'United Kingdom']);
        Country::create(['code' => 'UN', 'name' => 'United Nations']);
        Country::create(['code' => 'US', 'name' => 'United States']);
        Country::create(['code' => 'UY', 'name' => 'Uruguay']);
        Country::create(['code' => 'UZ', 'name' => 'Uzbekistan']);
        Country::create(['code' => 'VU', 'name' => 'Vanuatu']);
        Country::create(['code' => 'VA', 'name' => 'Vatican City']);
        Country::create(['code' => 'VE', 'name' => 'Venezuela']);
        Country::create(['code' => 'VN', 'name' => 'Vietnam']);
        Country::create(['code' => 'WF', 'name' => 'Wallis & Futuna']);
        Country::create(['code' => 'EH', 'name' => 'Western Sahara']);
        Country::create(['code' => 'YE', 'name' => 'Yemen']);
        Country::create(['code' => 'ZM', 'name' => 'Zambia']);
        Country::create(['code' => 'ZW', 'name' => 'Zimbabwe']);
    }
}
