<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Schema::disableForeignKeyConstraints();
        DB::table('countries')->truncate();

        Country::create(['name' => 'Afghanistan','code' => 'AF','phone_code' => '93']);
        Country::create(['name' => 'Åland Islands','code' => 'AX','phone_code' => '358']);
        Country::create(['name' => 'Albania','code' => 'AL','phone_code' => '355']);
        Country::create(['name' => 'Algeria','code' => 'DZ','phone_code' => '213']);
        Country::create(['name' => 'American Samoa','code' => 'AS','phone_code' => '1684']);
        Country::create(['name' => 'Andorra','code' => 'AD','phone_code' => '376']);
        Country::create(['name' => 'Angola','code' => 'AO','phone_code' => '244']);
        Country::create(['name' => 'Anguilla','code' => 'AI','phone_code' => '1264']);
        Country::create(['name' => 'Antarctica','code' => 'AQ','phone_code' => '0']);
        Country::create(['name' => 'Antigua & Barbuda','code' => 'AG','phone_code' => '1268']);
        Country::create(['name' => 'Argentina','code' => 'AR','phone_code' => '54']);
        Country::create(['name' => 'Armenia','code' => 'AM','phone_code' => '374']);
        Country::create(['name' => 'Aruba','code' => 'AW','phone_code' => '297']);
        Country::create(['name' => 'Ascension Island','code' => 'AC','phone_code' => '247']);
        Country::create(['name' => 'Australia','code' => 'AU','phone_code' => '61']);
        Country::create(['name' => 'Austria','code' => 'AT','phone_code' => '43']);
        Country::create(['name' => 'Azerbaijan','code' => 'AZ','phone_code' => '994']);
        Country::create(['name' => 'Bahamas','code' => 'BS','phone_code' => '1242']);
        Country::create(['name' => 'Bahrain','code' => 'BH','phone_code' => '973']);
        Country::create(['name' => 'Bangladesh','code' => 'BD','phone_code' => '880']);
        Country::create(['name' => 'Barbados','code' => 'BB','phone_code' => '1246']);
        Country::create(['name' => 'Belarus','code' => 'BY','phone_code' => '375']);
        Country::create(['name' => 'Belgium','code' => 'BE','phone_code' => '32']);
        Country::create(['name' => 'Belize','code' => 'BZ','phone_code' => '501']);
        Country::create(['name' => 'Benin','code' => 'BJ','phone_code' => '229']);
        Country::create(['name' => 'Bermuda','code' => 'BM','phone_code' => '1441']);
        Country::create(['name' => 'Bhutan','code' => 'BT','phone_code' => '975']);
        Country::create(['name' => 'Bolivia','code' => 'BO','phone_code' => '591']);
        Country::create(['name' => 'Bosnia & Herzegovina','code' => 'BA','phone_code' => '387']);
        Country::create(['name' => 'Botswana','code' => 'BW','phone_code' => '267']);
        Country::create(['name' => 'Brazil','code' => 'BR','phone_code' => '55']);
        Country::create(['name' => 'British Indian Ocean Territory','code' => 'IO','phone_code' => '246']);
        Country::create(['name' => 'British Virgin Islands','code' => 'VG','phone_code' => '1284']);
        Country::create(['name' => 'Brunei','code' => 'BN','phone_code' => '673']);
        Country::create(['name' => 'Bulgaria','code' => 'BG','phone_code' => '359']);
        Country::create(['name' => 'Burkina Faso','code' => 'BF','phone_code' => '226']);
        Country::create(['name' => 'Burundi','code' => 'BI','phone_code' => '257']);
        Country::create(['name' => 'Cambodia','code' => 'KH','phone_code' => '855']);
        Country::create(['name' => 'Cameroon','code' => 'CM','phone_code' => '237']);
        Country::create(['name' => 'Canada','code' => 'CA','phone_code' => '1']);
        Country::create(['name' => 'Canary Islands','code' => 'IC','phone_code' => '34']);
        Country::create(['name' => 'Cape Verde','code' => 'CV','phone_code' => '238']);
        Country::create(['name' => 'Caribbean Netherlands','code' => 'BQ','phone_code' => '599']);
        Country::create(['name' => 'Cayman Islands','code' => 'KY','phone_code' => '1345']);
        Country::create(['name' => 'Central African Republic','code' => 'CF','phone_code' => '236']);
        Country::create(['name' => 'Ceuta & Melilla','code' => 'EA','phone_code' => '34']);
        Country::create(['name' => 'Chad','code' => 'TD','phone_code' => '235']);
        Country::create(['name' => 'Chile','code' => 'CL','phone_code' => '56']);
        Country::create(['name' => 'China','code' => 'CN','phone_code' => '86']);
        Country::create(['name' => 'Christmas Island','code' => 'CX','phone_code' => '61']);
        Country::create(['name' => 'Cocos (Keeling) Islands','code' => 'CC','phone_code' => '672']);
        Country::create(['name' => 'Colombia','code' => 'CO','phone_code' => '57']);
        Country::create(['name' => 'Comoros','code' => 'KM','phone_code' => '269']);
        Country::create(['name' => 'Congo - Brazzaville','code' => 'CG','phone_code' => '242']);
        Country::create(['name' => 'Congo - Kinshasa','code' => 'CD','phone_code' => '242']);
        Country::create(['name' => 'Cook Islands','code' => 'CK','phone_code' => '682']);
        Country::create(['name' => 'Costa Rica','code' => 'CR','phone_code' => '506']);
        Country::create(['name' => 'Côte d’Ivoire','code' => 'CI','phone_code' => '225']);
        Country::create(['name' => 'Croatia','code' => 'HR','phone_code' => '385']);
        Country::create(['name' => 'Cuba','code' => 'CU','phone_code' => '53']);
        Country::create(['name' => 'Curaçao','code' => 'CW','phone_code' => '599']);
        Country::create(['name' => 'Cyprus','code' => 'CY','phone_code' => '357']);
        Country::create(['name' => 'Czechia','code' => 'CZ','phone_code' => '420']);
        Country::create(['name' => 'Denmark','code' => 'DK','phone_code' => '45']);
        Country::create(['name' => 'Diego Garcia','code' => 'DG','phone_code' => '246']);
        Country::create(['name' => 'Djibouti','code' => 'DJ','phone_code' => '253']);
        Country::create(['name' => 'Dominica','code' => 'DM','phone_code' => '1767']);
        Country::create(['name' => 'Dominican Republic','code' => 'DO','phone_code' => '1809']);
        Country::create(['name' => 'Ecuador','code' => 'EC','phone_code' => '593']);
        Country::create(['name' => 'Egypt','code' => 'EG','phone_code' => '20']);
        Country::create(['name' => 'El Salvador','code' => 'SV','phone_code' => '503']);
        Country::create(['name' => 'Equatorial Guinea','code' => 'GQ','phone_code' => '240']);
        Country::create(['name' => 'Eritrea','code' => 'ER','phone_code' => '291']);
        Country::create(['name' => 'Estonia','code' => 'EE','phone_code' => '372']);
        Country::create(['name' => 'Ethiopia','code' => 'ET','phone_code' => '251']);
        Country::create(['name' => 'Eurozone','code' => 'EZ','phone_code' => '00']);
        Country::create(['name' => 'Falkland Islands','code' => 'FK','phone_code' => '500']);
        Country::create(['name' => 'Faroe Islands','code' => 'FO','phone_code' => '298']);
        Country::create(['name' => 'Fiji','code' => 'FJ','phone_code' => '679']);
        Country::create(['name' => 'Finland','code' => 'FI','phone_code' => '358']);
        Country::create(['name' => 'France','code' => 'FR','phone_code' => '33']);
        Country::create(['name' => 'French Guiana','code' => 'GF','phone_code' => '594']);
        Country::create(['name' => 'French Polynesia','code' => 'PF','phone_code' => '689']);
        Country::create(['name' => 'French Southern Territories','code' => 'TF','phone_code' => '0']);
        Country::create(['name' => 'Gabon','code' => 'GA','phone_code' => '241']);
        Country::create(['name' => 'Gambia','code' => 'GM','phone_code' => '220']);
        Country::create(['name' => 'Georgia','code' => 'GE','phone_code' => '995']);
        Country::create(['name' => 'Germany','code' => 'DE','phone_code' => '49']);
        Country::create(['name' => 'Ghana','code' => 'GH','phone_code' => '233']);
        Country::create(['name' => 'Gibraltar','code' => 'GI','phone_code' => '350']);
        Country::create(['name' => 'Greece','code' => 'GR','phone_code' => '30']);
        Country::create(['name' => 'Greenland','code' => 'GL','phone_code' => '299']);
        Country::create(['name' => 'Grenada','code' => 'GD','phone_code' => '1473']);
        Country::create(['name' => 'Guadeloupe','code' => 'GP','phone_code' => '590']);
        Country::create(['name' => 'Guam','code' => 'GU','phone_code' => '1671']);
        Country::create(['name' => 'Guatemala','code' => 'GT','phone_code' => '502']);
        Country::create(['name' => 'Guernsey','code' => 'GG','phone_code' => '44']);
        Country::create(['name' => 'Guinea','code' => 'GN','phone_code' => '224']);
        Country::create(['name' => 'Guinea-Bissau','code' => 'GW','phone_code' => '245']);
        Country::create(['name' => 'Guyana','code' => 'GY','phone_code' => '592']);
        Country::create(['name' => 'Haiti','code' => 'HT','phone_code' => '509']);
        Country::create(['name' => 'Honduras','code' => 'HN','phone_code' => '504']);
        Country::create(['name' => 'Hong Kong SAR China','code' => 'HK','phone_code' => '852']);
        Country::create(['name' => 'Hungary','code' => 'HU','phone_code' => '36']);
        Country::create(['name' => 'Iceland','code' => 'IS','phone_code' => '354']);
        Country::create(['name' => 'India','code' => 'IN','phone_code' => '91']);
        Country::create(['name' => 'Indonesia','code' => 'ID','phone_code' => '62']);
        Country::create(['name' => 'Iran','code' => 'IR','phone_code' => '98']);
        Country::create(['name' => 'Iraq','code' => 'IQ','phone_code' => '964']);
        Country::create(['name' => 'Ireland','code' => 'IE','phone_code' => '353']);
        Country::create(['name' => 'Isle of Man','code' => 'IM','phone_code' => '44']);
        Country::create(['name' => 'Israel','code' => 'IL','phone_code' => '972']);
        Country::create(['name' => 'Italy','code' => 'IT','phone_code' => '39']);
        Country::create(['name' => 'Jamaica','code' => 'JM','phone_code' => '1876']);
        Country::create(['name' => 'Japan','code' => 'JP','phone_code' => '81']);
        Country::create(['name' => 'Jersey','code' => 'JE','phone_code' => '44']);
        Country::create(['name' => 'Jordan','code' => 'JO','phone_code' => '962']);
        Country::create(['name' => 'Kazakhstan','code' => 'KZ','phone_code' => '7']);
        Country::create(['name' => 'Kenya','code' => 'KE','phone_code' => '254']);
        Country::create(['name' => 'Kiribati','code' => 'KI','phone_code' => '686']);
        Country::create(['name' => 'Kosovo','code' => 'XK','phone_code' => '381']);
        Country::create(['name' => 'Kuwait','code' => 'KW','phone_code' => '965']);
        Country::create(['name' => 'Kyrgyzstan','code' => 'KG','phone_code' => '996']);
        Country::create(['name' => 'Laos','code' => 'LA','phone_code' => '856']);
        Country::create(['name' => 'Latvia','code' => 'LV','phone_code' => '371']);
        Country::create(['name' => 'Lebanon','code' => 'LB','phone_code' => '961']);
        Country::create(['name' => 'Lesotho','code' => 'LS','phone_code' => '266']);
        Country::create(['name' => 'Liberia','code' => 'LR','phone_code' => '231']);
        Country::create(['name' => 'Libya','code' => 'LY','phone_code' => '218']);
        Country::create(['name' => 'Liechtenstein','code' => 'LI','phone_code' => '423']);
        Country::create(['name' => 'Lithuania','code' => 'LT','phone_code' => '370']);
        Country::create(['name' => 'Luxembourg','code' => 'LU','phone_code' => '352']);
        Country::create(['name' => 'Macau SAR China','code' => 'MO','phone_code' => '853']);
        Country::create(['name' => 'Macedonia','code' => 'MK','phone_code' => '389']);
        Country::create(['name' => 'Madagascar','code' => 'MG','phone_code' => '261']);
        Country::create(['name' => 'Malawi','code' => 'MW','phone_code' => '265']);
        Country::create(['name' => 'Malaysia','code' => 'MY','phone_code' => '60']);
        Country::create(['name' => 'Maldives','code' => 'MV','phone_code' => '960']);
        Country::create(['name' => 'Mali','code' => 'ML','phone_code' => '223']);
        Country::create(['name' => 'Malta','code' => 'MT','phone_code' => '356']);
        Country::create(['name' => 'Marshall Islands','code' => 'MH','phone_code' => '692']);
        Country::create(['name' => 'Martinique','code' => 'MQ','phone_code' => '596']);
        Country::create(['name' => 'Mauritania','code' => 'MR','phone_code' => '222']);
        Country::create(['name' => 'Mauritius','code' => 'MU','phone_code' => '230']);
        Country::create(['name' => 'Mayotte','code' => 'YT','phone_code' => '269']);
        Country::create(['name' => 'Mexico','code' => 'MX','phone_code' => '52']);
        Country::create(['name' => 'Micronesia','code' => 'FM','phone_code' => '691']);
        Country::create(['name' => 'Moldova','code' => 'MD','phone_code' => '373']);
        Country::create(['name' => 'Monaco','code' => 'MC','phone_code' => '377']);
        Country::create(['name' => 'Mongolia','code' => 'MN','phone_code' => '976']);
        Country::create(['name' => 'Montenegro','code' => 'ME','phone_code' => '382']);
        Country::create(['name' => 'Montserrat','code' => 'MS','phone_code' => '1664']);
        Country::create(['name' => 'Morocco','code' => 'MA','phone_code' => '212']);
        Country::create(['name' => 'Mozambique','code' => 'MZ','phone_code' => '258']);
        Country::create(['name' => 'Myanmar (Burma)','code' => 'MM','phone_code' => '95']);
        Country::create(['name' => 'Namibia','code' => 'NA','phone_code' => '264']);
        Country::create(['name' => 'Nauru','code' => 'NR','phone_code' => '674']);
        Country::create(['name' => 'Nepal','code' => 'NP','phone_code' => '977']);
        Country::create(['name' => 'Netherlands','code' => 'NL','phone_code' => '31']);
        Country::create(['name' => 'New Caledonia','code' => 'NC','phone_code' => '687']);
        Country::create(['name' => 'New Zealand','code' => 'NZ','phone_code' => '64']);
        Country::create(['name' => 'Nicaragua','code' => 'NI','phone_code' => '505']);
        Country::create(['name' => 'Niger','code' => 'NE','phone_code' => '227']);
        Country::create(['name' => 'Nigeria','code' => 'NG','phone_code' => '234']);
        Country::create(['name' => 'Niue','code' => 'NU','phone_code' => '683']);
        Country::create(['name' => 'Norfolk Island','code' => 'NF','phone_code' => '672']);
        Country::create(['name' => 'North Korea','code' => 'KP','phone_code' => '850']);
        Country::create(['name' => 'Northern Mariana Islands','code' => 'MP','phone_code' => '1670']);
        Country::create(['name' => 'Norway','code' => 'NO','phone_code' => '47']);
        Country::create(['name' => 'Oman','code' => 'OM','phone_code' => '968']);
        Country::create(['name' => 'Pakistan','code' => 'PK','phone_code' => '92']);
        Country::create(['name' => 'Palau','code' => 'PW','phone_code' => '680']);
        Country::create(['name' => 'Palestinian Territories','code' => 'PS','phone_code' => '970']);
        Country::create(['name' => 'Panama','code' => 'PA','phone_code' => '507']);
        Country::create(['name' => 'Papua New Guinea','code' => 'PG','phone_code' => '675']);
        Country::create(['name' => 'Paraguay','code' => 'PY','phone_code' => '595']);
        Country::create(['name' => 'Peru','code' => 'PE','phone_code' => '51']);
        Country::create(['name' => 'Philippines','code' => 'PH','phone_code' => '63']);
        Country::create(['name' => 'Pitcairn Islands','code' => 'PN','phone_code' => '0']);
        Country::create(['name' => 'Poland','code' => 'PL','phone_code' => '48']);
        Country::create(['name' => 'Portugal','code' => 'PT','phone_code' => '351']);
        Country::create(['name' => 'Puerto Rico','code' => 'PR','phone_code' => '1787']);
        Country::create(['name' => 'Qatar','code' => 'QA','phone_code' => '974']);
        Country::create(['name' => 'Réunion','code' => 'RE','phone_code' => '262']);
        Country::create(['name' => 'Romania','code' => 'RO','phone_code' => '40']);
        Country::create(['name' => 'Russia','code' => 'RU','phone_code' => '70']);
        Country::create(['name' => 'Rwanda','code' => 'RW','phone_code' => '250']);
        Country::create(['name' => 'Samoa','code' => 'WS','phone_code' => '684']);
        Country::create(['name' => 'San Marino','code' => 'SM','phone_code' => '378']);
        Country::create(['name' => 'São Tomé & Príncipe','code' => 'ST','phone_code' => '239']);
        Country::create(['name' => 'Saudi Arabia','code' => 'SA','phone_code' => '966']);
        Country::create(['name' => 'Senegal','code' => 'SN','phone_code' => '221']);
        Country::create(['name' => 'Serbia','code' => 'RS','phone_code' => '381']);
        Country::create(['name' => 'Seychelles','code' => 'SC','phone_code' => '248']);
        Country::create(['name' => 'Sierra Leone','code' => 'SL','phone_code' => '232']);
        Country::create(['name' => 'Singapore','code' => 'SG','phone_code' => '65']);
        Country::create(['name' => 'Sint Maarten','code' => 'SX','phone_code' => '1']);
        Country::create(['name' => 'Slovakia','code' => 'SK','phone_code' => '421']);
        Country::create(['name' => 'Slovenia','code' => 'SI','phone_code' => '386']);
        Country::create(['name' => 'Solomon Islands','code' => 'SB','phone_code' => '677']);
        Country::create(['name' => 'Somalia','code' => 'SO','phone_code' => '252']);
        Country::create(['name' => 'South Africa','code' => 'ZA','phone_code' => '27']);
        Country::create(['name' => 'South Georgia & South Sandwich Islands','code' => 'GS','phone_code' => '0']);
        Country::create(['name' => 'South Korea','code' => 'KR','phone_code' => '82']);
        Country::create(['name' => 'South Sudan','code' => 'SS','phone_code' => '211']);
        Country::create(['name' => 'Spain','code' => 'ES','phone_code' => '34']);
        Country::create(['name' => 'Sri Lanka','code' => 'LK','phone_code' => '94']);
        Country::create(['name' => 'St. Barthélemy','code' => 'BL','phone_code' => '590']);
        Country::create(['name' => 'St. Helena','code' => 'SH','phone_code' => '290']);
        Country::create(['name' => 'St. Kitts & Nevis','code' => 'KN','phone_code' => '1869']);
        Country::create(['name' => 'St. Lucia','code' => 'LC','phone_code' => '1758']);
        Country::create(['name' => 'St. Martin','code' => 'MF','phone_code' => '590']);
        Country::create(['name' => 'St. Pierre & Miquelon','code' => 'PM','phone_code' => '508']);
        Country::create(['name' => 'St. Vincent & Grenadines','code' => 'VC','phone_code' => '1784']);
        Country::create(['name' => 'Sudan','code' => 'SD','phone_code' => '249']);
        Country::create(['name' => 'Suriname','code' => 'SR','phone_code' => '597']);
        Country::create(['name' => 'Svalbard & Jan Mayen','code' => 'SJ','phone_code' => '47']);
        Country::create(['name' => 'Swaziland','code' => 'SZ','phone_code' => '268']);
        Country::create(['name' => 'Sweden','code' => 'SE','phone_code' => '46']);
        Country::create(['name' => 'Switzerland','code' => 'CH','phone_code' => '41']);
        Country::create(['name' => 'Syria','code' => 'SY','phone_code' => '963']);
        Country::create(['name' => 'Taiwan','code' => 'TW','phone_code' => '886']);
        Country::create(['name' => 'Tajikistan','code' => 'TJ','phone_code' => '992']);
        Country::create(['name' => 'Tanzania','code' => 'TZ','phone_code' => '255']);
        Country::create(['name' => 'Thailand','code' => 'TH','phone_code' => '66']);
        Country::create(['name' => 'Timor-Leste','code' => 'TL','phone_code' => '670']);
        Country::create(['name' => 'Togo','code' => 'TG','phone_code' => '228']);
        Country::create(['name' => 'Tokelau','code' => 'TK','phone_code' => '690']);
        Country::create(['name' => 'Tonga','code' => 'TO','phone_code' => '676']);
        Country::create(['name' => 'Trinidad & Tobago','code' => 'TT','phone_code' => '1868']);
        Country::create(['name' => 'Tristan da Cunha','code' => 'TA','phone_code' => '290']);
        Country::create(['name' => 'Tunisia','code' => 'TN','phone_code' => '216']);
        Country::create(['name' => 'Turkey','code' => 'TR','phone_code' => '90']);
        Country::create(['name' => 'Turkmenistan','code' => 'TM','phone_code' => '7370']);
        Country::create(['name' => 'Turks & Caicos Islands','code' => 'TC','phone_code' => '1649']);
        Country::create(['name' => 'Tuvalu','code' => 'TV','phone_code' => '688']);
        Country::create(['name' => 'U.S. Outlying Islands','code' => 'UM','phone_code' => '1']);
        Country::create(['name' => 'U.S. Virgin Islands','code' => 'VI','phone_code' => '1340']);
        Country::create(['name' => 'Uganda','code' => 'UG','phone_code' => '256']);
        Country::create(['name' => 'Ukraine','code' => 'UA','phone_code' => '380']);
        Country::create(['name' => 'United Arab Emirates','code' => 'AE','phone_code' => '971']);
        Country::create(['name' => 'United Kingdom','code' => 'GB','phone_code' => '44']);
        Country::create(['name' => 'United Nations','code' => 'UN','phone_code' => '1']);
        Country::create(['name' => 'United States','code' => 'US','phone_code' => '1']);
        Country::create(['name' => 'Uruguay','code' => 'UY','phone_code' => '598']);
        Country::create(['name' => 'Uzbekistan','code' => 'UZ','phone_code' => '998']);
        Country::create(['name' => 'Vanuatu','code' => 'VU','phone_code' => '678']);
        Country::create(['name' => 'Vatican City','code' => 'VA','phone_code' => '39']);
        Country::create(['name' => 'Venezuela','code' => 'VE','phone_code' => '58']);
        Country::create(['name' => 'Vietnam','code' => 'VN','phone_code' => '84']);
        Country::create(['name' => 'Wallis & Futuna','code' => 'WF','phone_code' => '681']);
        Country::create(['name' => 'Western Sahara','code' => 'EH','phone_code' => '212']);
        Country::create(['name' => 'Yemen','code' => 'YE','phone_code' => '967']);
        Country::create(['name' => 'Zambia','code' => 'ZM','phone_code' => '260']);
        Country::create(['name' => 'Zimbabwe','code' => 'ZW','phone_code' => '263']);
    }
}
